kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  # Create the default user for the 'base-akka-kubernetes-ns' namespace, update for the namespace you are running in
- kind: User
  name: system:serviceaccount:base-akka-dev:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
